#+author: Leonardo Mascelli
#+title: rsedit

* Fixes todo
- [ ] electric-pair doesn't recognize a match pair in some case for example:
fn push_call_frame(&self, frame: &str) {
    self.call_stack
    .write()
    .expect("Failed to acquire write lock on call_stack")
    .push(frame.to_string());
}

this bug is still here. try to remove the open bracket after the function arguments
and add it again. a couple of brackets will be added (this is wrong) the closed bracket
is the one the close the function body. Also if you delete the wrong close bracket added
the open one is deleted.

* Macro todo 
- [ ] The editor structure is becoming too complex. I want to create compartiment
      that manage single aspects of the editor like buffers, layout, searches, commands,
      etc... so that a fail like the previous one where two windows where associated
      to the same buffer and one of them is closed cannot leave the other one with a
      pending reference to that buffer because the behavior of closing a window is 
      clearly managed by the layout manager. it is just a refactoring of the system.
- [ ] LSP integration
- [ ] Integrated terminal emulation

