#+author: Leonardo Mascelli
#+title: rsedit

* Working in progress.

* Fixes todo
- [ ] Mouse support: scrolling until the cursor goes out of the current view don't really
      move it so that after a keyboard move the view jumps back were it was and it's
      confusing.
- [ ] Is there a lock problem in log_diagnostic and enable_log_file? Try to learn something
      from it.
- [ ] Floating windows are drawn below window separators.
- [ ] Sometimes find file recursively doesn't work or anyway does not produce any completion.
      Inspect it please.

* Macro todo 
- [ ] Module dependency system (with functions like provide and requires) with a cached module
      table so that the same dependency is not loaded twice.
- [ ] Line numbers and decorator column for thing like breakpoint symbols or lsp warning
- [ ] Sort by type in dired mode (configurable via a lisp variable)
- [ ] All completions sources where it is possible should be filled asynchronously in the same
      loop where syntax-highlight sits.
- [ ] LSP integration
- [ ] Integrated terminal emulation

