//! Asking what something is.
//!
//! Equality in its three strengths -- `eq`, `eql`, `equal` -- and the type
//! questions. Most of these are one line each, generated by `predicate!`: see
//! `super`.
use super::*;

fn primitive_equal_impl<T: LispContext>(args: &[LispExp<T>]) -> Result<LispExp<T>, EvalError<T>> {
    exact_arity(args, 2)?;
    Ok(LispExp::boolean(args[0] == args[1]))
}

fn primitive_eq_impl<T: LispContext>(args: &[LispExp<T>]) -> Result<LispExp<T>, EvalError<T>> {
    exact_arity(args, 2)?;
    let is_eq = match (&args[0], &args[1]) {
        // Immediate values: compared by value, mirroring how real Elisp's
        // interned symbols and fixnums behave under `eq`.
        (LispExp::Number(a), LispExp::Number(b)) => a == b,
        (LispExp::Symbol(a), LispExp::Symbol(b)) => a == b,
        (a, b) if a.is_nil() && b.is_nil() => true,
        // Compound values: only `eq` if they're literally the same
        // allocation, not just structurally identical.
        (LispExp::Form(a), LispExp::Form(b)) => Arc::ptr_eq(a, b),
        // Two chains are `eq` when they are the same cell -- sharing a
        // tail is not enough, exactly as in real Elisp.
        (LispExp::Cons(a), LispExp::Cons(b)) => Arc::ptr_eq(a, b),
        (LispExp::Vector(a), LispExp::Vector(b)) => Arc::ptr_eq(a, b),
        (LispExp::Map(a), LispExp::Map(b)) => Arc::ptr_eq(a, b),
        (LispExp::String(a), LispExp::String(b)) => Arc::ptr_eq(a, b),
        _ => false,
    };
    Ok(LispExp::boolean(is_eq))
}

const EQ_DOC: &str = "(eq A B): Return t if A and B are the same object, nil otherwise.\n\n\
                 A number, a symbol and nil are compared by value; everything else is compared by \
                 identity, so two lists with the same elements are not `eq' unless they are the \
                 same list. Sharing a tail is not enough either. `equal' is the structural \
                 comparison.\n\n\
                 Example:\n\
                 (eq 'a 'a)         => t\n\
                 (eq '(1) '(1))     => nil\n\
                 (equal '(1) '(1))  => t";

const EQL_DOC: &str = "(eql A B): The same comparison as `eq'. Both names exist so that \
                 code carried over from other Lisps reads unchanged.\n\n\
                 Example:\n\
                 (eql 2 2) => t";

fn primitive_eq<T: LispContext>(
    args: &[LispExp<T>],
    _env: Arc<Env<T>>,
    _ctx: &T,
) -> Result<LispExp<T>, EvalError<T>> {
    primitive_eq_impl(args)
}

fn primitive_eql<T: LispContext>(
    args: &[LispExp<T>],
    _env: Arc<Env<T>>,
    _ctx: &T,
) -> Result<LispExp<T>, EvalError<T>> {
    primitive_eq_impl(args)
}

const EQUAL_DOC: &str = "(equal A B): Return t if A and B have the same structure and \
                 contents (deep, structural comparison), nil otherwise.\n\n\
                 Example:\n\
                 (equal '(1 2) '(1 2)) => t\n\
                 (equal \"ab\" \"ab\")    => t\n\
                 (equal '(1 2) '(1 3)) => nil";

fn primitive_equal<T: LispContext>(
    args: &[LispExp<T>],
    _env: Arc<Env<T>>,
    _ctx: &T,
) -> Result<LispExp<T>, EvalError<T>> {
    primitive_equal_impl(args)
}

const NULL_DOC: &str = "(null OBJECT): Return t if OBJECT is nil, nil otherwise.\n\n\
                 Example:\n\
                 (null nil)   => t\n\
                 (null '(1))  => nil";

fn primitive_null<T: LispContext>(
    args: &[LispExp<T>],
    _env: Arc<Env<T>>,
    _ctx: &T,
) -> Result<LispExp<T>, EvalError<T>> {
    exact_arity(args, 1)?;
    Ok(LispExp::boolean(args[0].is_nil()))
}

const NOT_DOC: &str = "(not OBJECT): Return t if OBJECT is nil, nil otherwise. \
                 Identical to `null`.\n\n\
                 Example:\n\
                 (not nil) => t\n\
                 (not t)   => nil";

fn primitive_not<T: LispContext>(
    args: &[LispExp<T>],
    env: Arc<Env<T>>,
    ctx: &T,
) -> Result<LispExp<T>, EvalError<T>> {
    // `not` and `null` are the same operation in Elisp.
    primitive_null(args, env, ctx)
}

const CONSP_DOC: &str = "(consp OBJECT): Return t if OBJECT is a cons cell -- a \
                 non-empty list or a dotted pair -- nil otherwise.\n\n\
                 Example:\n\
                 (consp '(1 2)) => t\n\
                 (consp nil)    => nil\n\
                 (consp 5)      => nil";

predicate!(primitive_consp, LispExp::Cons(_));

const LISTP_DOC: &str = "(listp OBJECT): Return t if OBJECT is a list -- a cons cell or \
                 nil, the empty list -- and nil otherwise.\n\n\
                 A *form* is not a list to this predicate. The two look alike when printed and \
                 are different things: a form is syntax waiting to be evaluated, and it has no \
                 `car'. Anything handing a form to Lisp as data converts it first, which is why \
                 a binding read back with `key-binding' can be taken apart.\n\n\
                 Example:\n\
                 (listp '(1 2)) => t\n\
                 (listp nil)    => t\n\
                 (listp \"ab\")   => nil";

fn primitive_listp<T: LispContext>(
    args: &[LispExp<T>],
    _env: Arc<Env<T>>,
    _ctx: &T,
) -> Result<LispExp<T>, EvalError<T>> {
    exact_arity(args, 1)?;
    Ok(LispExp::boolean(is_list_value(&args[0])))
}

const STRINGP_DOC: &str = "(stringp OBJECT): Return t if OBJECT is a string, nil \
                 otherwise.\n\n\
                 Example:\n\
                 (stringp \"hi\") => t\n\
                 (stringp 5)    => nil";

predicate!(primitive_stringp, LispExp::String(_));

const NUMBERP_DOC: &str = "(numberp OBJECT): Return t if OBJECT is a number, nil \
                 otherwise.\n\n\
                 Example:\n\
                 (numberp 5)     => t\n\
                 (numberp \"5\")   => nil";

predicate!(primitive_numberp, LispExp::Number(_));

const SYMBOLP_DOC: &str = "(symbolp OBJECT): Return t if OBJECT is a symbol, nil \
                 otherwise.\n\n\
                 Example:\n\
                 (symbolp 'foo) => t\n\
                 (symbolp \"foo\") => nil";

predicate!(primitive_symbolp, LispExp::Symbol(_));

const FUNCTIONP_DOC: &str = "(functionp OBJECT): Return t if OBJECT can be called: a \
                 lambda, a primitive, or a symbol naming either. nil otherwise.\n\n\
                 The function namespace's half of `boundp', which asks the same thing of the \
                 variable one. A name can be bound in one, in both, or in neither.\n\n\
                 Example:\n\
                 (functionp 'car)          => t\n\
                 (functionp (lambda () 1)) => t\n\
                 (functionp 'no-such-fn)   => nil";

fn primitive_functionp<T: LispContext>(
    args: &[LispExp<T>],
    env: Arc<Env<T>>,
    _ctx: &T,
) -> Result<LispExp<T>, EvalError<T>> {
    exact_arity(args, 1)?;
    let is_function = match &args[0] {
        LispExp::Lambda(_) | LispExp::Primitive { .. } => true,
        LispExp::Symbol(name) => env.get_function(name).is_some(),
        _ => false,
    };
    Ok(LispExp::boolean(is_function))
}

const VECTORP_DOC: &str = "(vectorp OBJECT): Return t if OBJECT is a vector, nil \
                 otherwise.\n\n\
                 Example:\n\
                 (vectorp [1 2 3]) => t\n\
                 (vectorp '(1 2))  => nil";

predicate!(primitive_vectorp, LispExp::Vector(_));

const ZEROP_DOC: &str = "(zerop NUMBER): Return t if NUMBER is zero, nil otherwise.\n\n\
                 Example:\n\
                 (zerop 0) => t\n\
                 (zerop 1) => nil";

fn primitive_zerop<T: LispContext>(
    args: &[LispExp<T>],
    _env: Arc<Env<T>>,
    _ctx: &T,
) -> Result<LispExp<T>, EvalError<T>> {
    exact_arity(args, 1)?;
    Ok(LispExp::boolean(expect_number(&args[0])? == 0.0))
}

const ATOM_DOC: &str = "(atom OBJECT): Return t if OBJECT is not a cons cell, nil if it \
                 is. Everything that is not a list is an atom, including nil.\n\n\
                 Not to be confused with `make-atom', which builds a mutable box shared between \
                 threads.\n\n\
                 Example:\n\
                 (atom 1)      => t\n\
                 (atom nil)    => t\n\
                 (atom '(1 2)) => nil";

predicate!(primitive_atom_predicate, not LispExp::Cons(_));

/// Register this module's primitives: asking what something is.
///
/// Called by [`super::setup_base_env`]. Here rather than there because a
/// primitive's name, its implementation and its docstring are one fact in three
/// pieces, and they were a thousand lines apart.
pub(super) fn install<T: LispContext>(into: &Registry<T>) {
    // ------------------------------- Predicates ------------------------------
    // `eq`/`eql` are left undocumented: both are currently implemented as
    // structural (deep) equality, the same as `equal`, rather than the
    // identity/type-aware comparisons real Elisp specifies. `functionp` is
    // also left undocumented: real Elisp resolves a symbol argument through
    // `fboundp` (so `(functionp 'car)` is t), but this implementation only
    // recognizes already-callable values, so it always says nil for a quoted
    // symbol.
    into.function("eq", primitive_eq, EQ_DOC);
    into.function("eql", primitive_eql, EQL_DOC);
    into.function("equal", primitive_equal, EQUAL_DOC);
    into.function("null", primitive_null, NULL_DOC);
    into.function("not", primitive_not, NOT_DOC);
    into.function("consp", primitive_consp, CONSP_DOC);
    into.function("listp", primitive_listp, LISTP_DOC);
    into.function("stringp", primitive_stringp, STRINGP_DOC);
    into.function("numberp", primitive_numberp, NUMBERP_DOC);
    into.function("symbolp", primitive_symbolp, SYMBOLP_DOC);
    into.function("functionp", primitive_functionp, FUNCTIONP_DOC);
    into.function("vectorp", primitive_vectorp, VECTORP_DOC);
    into.function("zerop", primitive_zerop, ZEROP_DOC);
    into.function("atom", primitive_atom_predicate, ATOM_DOC);
}
